### ISSUE TITLE
Where are the binaries?

### ISSUE THREAD

**Issue by wolph** [millenomi/afloat#8] opened 2013-12-15 12:35 UTC
It seems that only the source is available here and the website links back to the GIthub page.

**Comment by it-ony** [comment] 2014-01-19 21:32
Good question. 

Please provide a README.md, how to compile the programm. 
It would be also nice, if you would add it to [homebrew](https://github.com/Homebrew/homebrew).

**Comment by millenomi** [comment] 2014-01-20 01:38
Duplicate of issue #6.

**Closed as completed by millenomi** 2014-01-20 01:38 UTC
